import axios from 'axios';

// Generated by https://quicktype.io
export interface Generaciones {
    total: number;
    results:  Result[];
}

export interface Result {
    generacion:                      string;
    cantidad_estudiantes_con_rezago: number;
    fecha_ingreso:                   string;
    fecha_egreso:                    null | string;
}


export const getGeneraciones = async (page: number = 1, perPage: number = 10): Promise<Generaciones> => {
    try {
        console.log("hola")
        const rowData = await axios.get<Generaciones>(`https://urchin-app-mm9rx.ondigitalocean.app/api/v1/cohortes?page=${page}&page_size=${perPage}`);
        const data = rowData.data
        console.log("hola")
        console.log(rowData.data)
        console.log(rowData)
        return data
    } catch (error) {
        console.error("Ocurrió un error al obtener las generaciones:", error);
        throw new Error(`${error}`); 
    }
};


